### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by lazezo2** [pablouser1/SignTok#1]
is this code correct?

```
(import requests

headers = {
    user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
    'body': 'tiktok url',

}
u="https://signtok.vercel.app:8080/signature"

r = requests.post(u, headers=headers)
print(r)
print(r.text)
#print(r.json()))
```
because it gave error connection closed...

is this working with the new tiktok api?
is there any demo at Heroku or similar?

**Comment by pablouser1** [comment]
Hi,

1. That url is not correct. You have to use https://signtok.vercel.app/api/signature (vercel requires that /api for the serverless functions)
2. You have to send a 'data' parameter for the POST payload
3. You don't _need_ to send a custom user-agent, the program will handle that for you.

So, fixing those issues your code should look like this:
```python
import requests

data = 'tiktok_url'

u = "https://signtok.vercel.app/api/signature"

r = requests.post(u, data=data)
print(r.json())

```
I'll write some documentation for usage

> is this working with the new tiktok api?

Yes, at least for now it can generate valid _signature and x-tt-params

> is there any demo at Heroku or similar?

I had one on Heroku but I ended up moving it to Vercel because it would exceed my cuota, but I'm planning to make an [app.json](https://devcenter.heroku.com/articles/app-json-schema) to make hosting an instance easier.

**Comment by lazezo2** [comment]
You are the star, that's working very well, thank you very much

**Comment by gaplan** [comment]
Hi There,
How can we post the data to tiktok ?
any sample with Python ?
Thank you.

**Comment by zakrian07** [comment]
when we got signed url this is not giving us data any help ?
